services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - '27017:27017'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 10s
      retries: 10
    volumes:
      - db-data:/data/db
    networks:
      - default

networks: 
  default:
   name: mongo-net
volumes:
  db-data:
    name: "mongodb-data"
